stages:
  - build
  - test
  - cleanup

build:
  stage: build
  image: docker:stable
  script:
    - docker build --tag $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .

PyLint test:
  stage: test
  image: docker:stable
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA pylint --version

wheel test:
  stage: test
  image: docker:stable
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA wheel version

cleanup:
  stage: cleanup
  image: docker:stable
  script:
    - docker rmi $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
